name: "Build"
on:
  workflow_call:
    inputs:
      for_deploy:
        required: true
        type: boolean
  workflow_dispatch:
  pull_request:
    paths:
      - Dockerfile
      - .dockerignore
      - entrypoint/**
      - .github/workflows/**.yml
  push:
    tags: [ "v*.*.*" ]

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: "Checkout Git Repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Log in to GitHub Container Registry"
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Extract metadata"
        id: meta
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

      - name: "Build Docker Image"
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          tags: ${{ github.ref_type == 'tag' && steps.meta.outputs.tags || 'amp-dockerized:latest' }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref_type == 'tag' }}
          outputs: ${{ github.ref_type != 'tag' && format('type=docker,dest=/tmp/docker-image-{0}.tar', matrix.arch) || '' }}

      - name: "Upload Docker Image Artifact"
        if: ${{ inputs.for_deploy == true }}
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.arch }}
          path: /tmp/docker-image-${{ matrix.arch }}.tar